Staplesfast/urls.py
from django.contrib import admin
from django.urls import path, include
from core.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index),
    path('core/', include("core.urls", 'core')),
    path('accounts/', include('allauth.urls')),
]

core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('index/', views.index, name='index'),
    path('register/', views.register, name='register'),
    path('signup/', views.signup_view, name='signup'),
]

core/models.py
from django.db import models
from django.contrib.auth.models import (
    BaseUserManager, AbstractBaseUser, PermissionsMixin
)


class UserManager(BaseUserManager):
    """
    A user manager that provides helper functions to created users
    """

    def create_user(self, email, password, **extra_fields):
        """
        Function to create a user
        """
        if not email:
            raise ValueError("Please provide an valid email address")
        email = self.normalize_email(email)   # makes the email all lower caps
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)

        return user

    def create_superuser(self, email, password):
        """
        creates a superuser for the system
        """
        user = self.create_user(email, password)
        user.is_superuser = True
        user.is_staff = True
        user.save(using=self._db)

        return user


class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(
        verbose_name='Email Address',
        max_length=255,
        unique=True,
        null=False,
    )
    password = models.CharField(max_length=255, null=False)
    username = models.CharField(max_length=255, verbose_name='Name')
    address = models.CharField(max_length=400)
    city = models.CharField(max_length=255)
    postal_code = models.CharField(max_length=255)
    phone_number = models.CharField(max_length=255)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)  # a admin user; non super-user
    is_superuser = models.BooleanField(default=False)  # a superuser
    # notice the absence of a "Password field", that is built in.

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = [username, address, city, postal_code, phone_number]  # Email & Password are required by default.
    objects = UserManager()

    def get_full_name(self):
        # The user is identified by their email address
        return self.username

    # def get_short_name(self):
    #     # The user is identified by their email address
    #     return self.first_name

    def __str__(self):              # __unicode__ on Python 2
        return self.email

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True

    # @property
    # def is_staff(self):
    #     "Is the user a member of staff?"
    #     return self.is_staff
    #
    # @property
    # def is_superuser(self):
    #     "Is the user a admin member?"
    #     return self.is_superuser
    #
    # @property
    # def is_active(self):
    #     "Is the user active?"
    #     return self.is_active

core/forms.py
from django import forms
from .models import User


class SignupForm(forms.ModelForm):
    confirm_password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ['email', 'password', 'confirm_password', 'username', 'address', 'city', 'postal_code', 'phone_number']

    def clean(self):
        cleaned_data = super(SignupForm, self).clean()
        password = cleaned_data.get("password")
        confirm_password = cleaned_data.get("confirm_password")

        if password != confirm_password:
            raise forms.ValidationError(
                "password and confirm_password does not match"
            )

core/views.py
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect
from .forms import SignupForm


def index(request):
    """
    renders the index page view : Home Page
    """
    context_dict = {}
    response = render(request, 'index.html', context=context_dict)
    return response


def register(request):
    return render(request, 'register.html')


def signup_view(request):
    if request.method == "POST":
        form = SignupForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.set_password(user.password)
            user.save()
            email = form.cleaned_data.get('email')
            password = form.cleaned_data.get('password')
            user = authenticate(username=email, password=password)
            login(request, user)
            return redirect('core:index')
    else:
        form = SignupForm()
    return render(request, 'account/signup.html', {'form': form})

templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Staplefast</title>
    <link rel="stylesheet" href="{% static 'css/project.css' %}">
       <link rel="shortcut icon" href="{% static 'images/staplesfast_favicon.png' %}" type="image/x-icon">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>

<body>
    <div class="wrapper">
        <div class="navbar">
        <img class="brand-name" src="{% static 'images/logo.png' %}" alt="Logo">
        <div class="toggle-button">
            <span class="bar"></span>
            <span class="bar"></span>
            <span class="bar"></span>
        </div>
         <div class="navbar-links2">
            <ul>
                <a href="#"> <li>HOW IT WORKS</li></a>
                {% if not user.is_authenticated %}
                <a href="{% url 'core:signup' %}"> <li>REGISTER</li></a>
                {% endif %}
                <a href="#" id="js-header-buy-btn"> <li>BUY NOW</li></a>
                <div class="login-div">
                    {% if user.is_authenticated %}
                        <a href="/accounts/logout"><li class="navigation-link navigation-login-button">LOGOUT</li></a>
                    {% else %}
                        <a href="/accounts/login"><li class="navigation-link navigation-login-button">LOGIN</li></a>
                    {% endif %}
</div>
            </ul>
        </div>
        <div class="navbar-links">
            <ul>
               <a href="#"> <li>HOW IT WORKS</li></a>
                {% if not user.is_authenticated %}
               <a href="{% url 'core:signup' %}">  <li>REGISTER</li></a>
                {% endif %}
                <a href="#"  id="js-header-buy-btn"> <li>BUY NOW</li></a>
                
                <li class="navigation-link navigation-login-left-div">dsd</li>
                {% if user.is_authenticated %}
                <a href="/accounts/logout" class="navigation-link navigation-login-button">LOGOUT</a>
                {% else %}
                <a href="/accounts/login" class="navigation-link navigation-login-button">LOGIN</a>
                {% endif %}
            </ul>
        </div>
    </div>
    <div class="content">


        <div class="box1">
            <img class="fridge-image" src="{% static 'images/fridge.png' %}" alt="Fridge png">

            <h2>THE PROBLEM</h2>
            <p id="random">The new normal has changed our grocery habits. This has often reduced trips and in turn lead to mid week shortages. </p>

        </div>

        <div class="box2">
            <img class="food-image" src="{% static 'images/food.png' %}" alt="Food png">
            <h2>WHAT IF...</h2>
            <p id="random">You could have only the most important staples delivered to your door disinfected and ready to consume. </p>

        </div>

        <div class="box3">
            <img class="van-image" src="{% static 'images/van.png' %}" alt="Van png">
            <h2 id="solution-text">THE SOLUTION</h2>
            <p id="random2">Same day delivery of fridge staples from staplesfast.com. </p>

        </div>

    </div>




    <div class="second-content-div">


        <div class="box1">


            <h2 id="how-it-text">HOW IT WORKS</h2>
            <div class="list-div">
                <p class="grocery-text"> Each reusable box contains:</p>
                <li class="grocery-text">8 Litres of partly skimmed Milk </li>
                <li class="grocery-text"> 2 Loafs of wonder bread </li>
               <li class="grocery-text"> 450 grams of brand salted butter </li>
                <li class="grocery-text"> Dozen farm fresh eggs </li>
                
                 

            </div>
        </div>

        <div class="box2">
            <img class="candy-image" src="{% static 'images/candy (2).jpg' %}" alt="candy png">

        </div>

        <div class="box3">
            <h1 class="price-text">$50 Including Tax and Delivery </h1>

        </div>

    </div>


    <div class="button-div">
        <button id="js-my-buy-btn" class="cart-button">Add to Cart and Pay Now</button>
        <div id='product-component-1591813487900' style="display: none"></div>
    </div>
        <!-- Shopify But Button -->

        <!-- End Buy Button -->
    <div class="form-div">
        <div class="first-div">
            <div class="contact-info">
                <p class="hidden-number">XXX-XXX-XXX</p>
                <p class="email-text">info@staplefast.com</p>
                <div class="social-icons-div">

                    <div class="icons"><i class="fa fa-facebook-f"></i></div>
                    <div class="icons"> <i class="fa fa-twitter"></i></div>
                    <div class="icons"> <i class="fa fa-instagram"></i></div>


                </div>

                <div class="link-pages">
                    <a href="#" class="faq-page">FAQ</a>
                    <a href="#" class="faq-page">LEGAL</a>
                </div>
            </div>

        </div>

        <div class="contact-form">

            <div class="resgister-div">
                <p class="contact-form-text">CONTACT US</p>
                <div class="inputs">
                    <input type="text" placeholder="First Name">
                    <input type="text" placeholder="Last Name">
                    <input type="email" placeholder="Email">
                    <input type="tel" placeholder="Phone Number">
                </div>

                <textarea name="" id="" cols="77" rows="10" placeholder="Please Enter Your Message"></textarea>
                <div class="submit-button-div">   <button class="submit">Submit</button></div>
             
               
                 
            </div>


        </div>
        
    </div>
<div class="copyright-div">
         <p class="copyright-text">Copyright © 2020 staplesfast.com Inc. All rights reserved. </p>
         </div>
    </div>
    <script type="text/javascript" src="{% static 'js/clickButton.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/shopifyBuyButton.js' %}"></script> <!-- Shopify Buy Button -->
   <script>
        const toggleButton = document.getElementsByClassName('toggle-button')[0]
        const navbarLinks = document.getElementsByClassName('navbar-links2')[0]

        toggleButton.addEventListener('click', () => {
            navbarLinks.classList.toggle('active')
        })
    </script>

</body>
</html>

templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Staplesfast | Login </title>
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
    <link rel="shortcut icon" href="{% static 'images/staplesfast_favicon.png' %}" type="image/x-icon">

    <script src="https://kit.fontawesome.com/5a01f232c4.js" crossorigin="anonymous"></script>
</head>
<body>
           <div class="navbar">
        <img class="brand-name" src="{% static 'images/logo.png' %}" alt="Logo Png">
        <div class="toggle-button">
            <span class="bar"></span>
            <span class="bar"></span>
            <span class="bar"></span>
        </div>
         <div class="navbar-links2">
            <ul>
                <a href="#"> <li>HOW IT WORKS</li></a>
                <a href="register.html"> <li>REGISTER</li></a>
                <a href="payment.html" id="js-header-buy-btn"> <li>BUY NOW</li></a>
                <div class="login-divs">
               <a href="login.html">  <li class="navigation-link navigation-login-button">LOGIN</li></a>
            
</div>
            </ul>
        </div>
        <div class="navbar-links">
            <ul>
               <a href="#"> <li>HOW IT WORKS</li></a>
               <a href="register.html">  <li>REGISTER</li></a>
                <a href="payment.html" id="js-header-buy-btn"> <li>BUY NOW</li></a>
                
                <li class="navigation-link navigation-login-left-div">dsd</li>
            <a href="#" class="navigation-link navigation-login-button">LOGIN</a>

            </ul>
        </div>
    </div>
  
    
    
    <div class="login-page-div">
        
   
    <div class="login-div">
    <div class="login-div-text">
    <h1 class="login-text">LOGIN</h1>
    </div>
    <div class="input-data">
    <div class="email-div">
   <!-- <p class="email-heading">Email</p>-->
    <input type="email" class="email-field" placeholder="Enter your email">
    </div>
     <div class="password-div">
   <!-- <p class="email-heading">Password</p>-->
    <input type="password" class="email-field" placeholder="Enter your password">
    </div>
     </div>
      </div>
      
      <div class="forgot-password">
          <div class="checkbox-div">
              <input type="checkbox" class="checkbox">
               <p class="keep-me-login-text">
            Keep me logged in
          </p>
          </div>
          
         
          <div class="forgot-password-div">
            <p class="forgot-pass-text">Forgot Password?</p>
          </div>
      </div>
      
      <div class="button-div">
                <button class="login-button">Login</button>
            </div>
            
            <div class="dont-div">
                <p class="dont-you-text">Don't Have an Account?</p>
                <a href="register.html" class="register">Register</a>
            </div>
         
             
                <div class="form-div">
        <div class="first-div">
            <div class="contact-info">
                <div class="social-icons-div">

                    <div class="icons"><i class="fa fa-facebook-f"></i></div>
                    <div class="icons"> <i class="fa fa-twitter"></i></div>
                    <div class="icons"> <i class="fa fa-instagram"></i></div>


                </div>

                <div class="link-pages">
                    <a href="#" class="faq-page">FAQ</a>
                    <a href="#" class="faq-page">LEGAL</a>
                    <!-- Shopify But Button's div but it wont appear as display is none -->
                    <div id='product-component-1591813487900' style="display: none"></div>
                </div>
            </div>

        </div>
        <div class="second-div">
             <p class="copyright-text">Copyright © 2020 staplesfast.com Inc. All rights reserved. </p>
        </div>
    </div>
          </div>
       <script>
        const toggleButton = document.getElementsByClassName('toggle-button')[0]
        const navbarLinks = document.getElementsByClassName('navbar-links2')[0]

        toggleButton.addEventListener('click', () => {
            navbarLinks.classList.toggle('active')
        })
    </script>
    <script type="text/javascript" src="{% static 'js/authPagesClickButton.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/shopifyBuyButton.js' %}"></script> <!-- Shopify Buy Button -->
</body>
</html>

templates/payment.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Staplefast | Payment</title>
      <link rel="shortcut icon" href="./assets/staplesfast_favicon.png" type="image/x-icon">
    <link rel="stylesheet" href="payment.css">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>

<body>
      <div class="navbar">
        <img class="brand-name" src="assets/logo.png" alt="">
        <div class="toggle-button">
            <span class="bar"></span>
            <span class="bar"></span>
            <span class="bar"></span>
        </div>
         <div class="navbar-links2">
            <ul>
                <a href="#"> <li>HOW IT WORKS</li></a>
                <a href="register.html" target="_blank"> <li>REGISTER</li></a>
                <a href="payment.html" target="_blank"> <li>BUY NOW</li></a>
                <div class="login-div">
               <a href="login.html" target="_blank">  <li class="navigation-link navigation-login-button">LOGIN</li></a>
            
</div>
            </ul>
        </div>
        <div class="navbar-links">
            <ul>
               <a href="#"> <li>HOW IT WORKS</li></a>
               <a href="register.html" target="_blank">  <li>REGISTER</li></a>
                <a href="payment.html" target="_blank"> <li>BUY NOW</li></a>
                
                <li class="navigation-link navigation-login-left-div">dsd</li>
            <a href="login.html" class="navigation-link navigation-login-button" target="_blank">LOGIN</a>

            </ul>
        </div>
    </div>


    <div class="wrapper">
        <div class="payment-text-div">
            <h1 class="payment-text">PAYMENT METHOD</h1>
        </div>

        <div class="details-div">
            <div class="forgot-password">
                <div class="checkbox-div">
                    <input type="radio" class="radio">
                    <p class="keep-me-login-text">
                        Credit & Debit Cards
                    </p>
                </div>


                <div class="forgot-password-div">
                    <p class="forgot-pass-text"><i class="fa fa-cc-visa"></i></p>
                    <p class="forgot-pass-text"><i class="fa fa-cc-mastercard"></i></p>
                </div>
            </div>

            <div class="input-data">
                <div class="email-div">

                    <input type="text" class="email-field" placeholder="Enter cardholder name">



                    <input type="text" class="email-field" placeholder="Enter card number">

                </div>
            </div>

            <div class="select-div">

                <select class="month">
                    <option>Month</option>
                    <option value="January">January</option>
                    <option value="Febuary">Febuary</option>
                    <option value="March">March</option>
                    <option value="April">April</option>
                    <option value="May">May</option>
                    <option value="June">June</option>
                    <option value="July">July</option>
                    <option value="August">August</option>
                    <option value="September">September</option>
                    <option value="October">October</option>
                    <option value="November">November</option>
                    <option value="December">December</option>
                </select>
                <select class="year">
                    <option>Year</option>
                    <option value="2018">2018</option>
                    <option value="2018">2019</option>
                    <option value="2018">2020</option>
                    <option value="2018">2021</option>
                    <option value="2018">2022</option>
                    <option value="2018">2023</option>
                    <option value="2018">2024</option>
                    <option value="2018">2025</option>
                    <option value="2018">2026</option>
                    <option value="2018">2027</option>
                    <option value="2018">2028</option>
                    <option value="2018">2029</option>
                    <option value="2018">2030</option>
                    <option value="2018">2031</option>
                    <option value="2018">2032</option>
                    <option value="2018">2033</option>
                    <option value="2018">2034</option>
                    <option value="2018">2035</option>
                    <option value="2018">2036</option>
                    <option value="2018">2037</option>
                    <option value="2018">2038</option>
                    <option value="2018">2039</option>

                </select>


                <div class="cvv-div">
                    <input type="password" class="cvv" placeholder="CVV" maxlength="3">
                    <div class="info-circle"> <i class="fa fa-info-circle"></i></div>
                    <p>3 digits</p>
                </div>
            </div>


            <div class="checkbox-div2">
                <input type="checkbox" id="checkbox">
                 <label for="checkbox"><p class="keep-me-login-text">
                    I have read and accept the terms of use and privacy policy
                </p>
                </label>
  

                
            </div>

            <div class="button-div">
                <button class="login-button">Pay Now</button>
            </div>
        </div>

        <div class="forgot-passwords">
            <div class="checkbox-div3">
                <input type="radio" class="radios3" name="payment" value="paypal">
                <p class="keep-me-login-text">
                    Paypal
                </p>
            </div>


            <div class="forgot-password-div">
                <p class="forgot-pass-texts"><i class="fa fa-cc-paypal"></i></p>

            </div>
        </div>

        <div class="forgot-passwords">
            <div class="checkbox-div3">
                <input type="radio" class="radios2" name="payment" value="bitcoin">
                <p class="keep-me-login-text">
                    Bitcoin
                </p>
            </div>


            <div class="forgot-password-div">
                <p class="forgot-pass-text2"><i class="fa fa-bitcoin"></i></p>
            </div>
        </div>

        <div class="forgot-passwords">
            <div class="checkbox-div3">
                <input type="radio" class="radios" name="payment" value="interac">
                <p class="keep-me-login-text">
                    Interac e-transfer
                </p>
            </div>


            <div class="forgot-password-div">
                <img src="interac.jpg" alt="" class="interac">

            </div>
        </div>




        <div class="form-div">
            <div class="first-div">
                <div class="contact-info">
                    <div class="social-icons-div">

                        <div class="icons"><i class="fa fa-facebook-f"></i></div>
                        <div class="icons"> <i class="fa fa-twitter"></i></div>
                        <div class="icons"> <i class="fa fa-instagram"></i></div>


                    </div>

                    <div class="link-pages">
                        <a href="#" class="faq-page">FAQ</a>
                        <a href="#" class="faq-page">LEGAL</a>
                    </div>
                </div>

            </div>
            <div class="second-div">
                <p class="copyright-text">Copyright © 2020 staplesfast.com Inc. All rights reserved. </p>
            </div>
        </div>
    </div>


      <script>
        const toggleButton = document.getElementsByClassName('toggle-button')[0]
        const navbarLinks = document.getElementsByClassName('navbar-links2')[0]

        toggleButton.addEventListener('click', () => {
            navbarLinks.classList.toggle('active')
        })
    </script>

</body>

</html>

templates/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Staplefast | Register</title>
      <link rel="shortcut icon" href="{% static 'images/staplesfast_favicon.png' %}" type="image/x-icon">
    <link rel="stylesheet" href="{% static 'css/register.css' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>

<body>
      <div class="navbar">
        <img class="brand-name" src="{% static 'images/logo.png' %}" alt="Logo png">
        <div class="toggle-button">
            <span class="bar"></span>
            <span class="bar"></span>
            <span class="bar"></span>
        </div>
         <div class="navbar-links2">
            <ul>
                <a href="#"> <li>HOW IT WORKS</li></a>
                <a href="register.html"> <li>REGISTER</li></a>
                <a href="#" id="js-header-buy-btn"> <li>BUY NOW</li></a>
                <div class="login-div">
               <a href="login.html">  <li class="navigation-link navigation-login-button">LOGIN</li></a>

</div>
            </ul>
        </div>
        <div class="navbar-links">
            <ul>
               <a href="#"> <li>HOW IT WORKS</li></a>
               <a href="register.html">  <li>REGISTER</li></a>
                <a href="#" id="js-header-buy-btn"> <li>BUY NOW</li></a>

                <li class="navigation-link navigation-login-left-div">dsd</li>
            <a href="login.html" class="navigation-link navigation-login-button">LOGIN</a>

            </ul>
        </div>
    </div>

    <div class="wrapper">
        <div class="register-text-div">
            <h1 class="register-text">REGISTER</h1>
        </div>
               <div class="input-data">
                <div class="email-div">
                    <div>

                    </div>
                    <p class="name">Name</p>
                    <input type="text" class="email-field" placeholder="Enter your name" required>
                     <p class="name">Email</p>
                    <input type="email" class="email-field" placeholder="Enter your email">
                     <p class="name">Address</p>
                     <input type="text" class="email-field" placeholder="Enter your address">
                      <p class="name">City</p>
                      
                      <input type="text" class="email-field" placeholder="Enter your city name">
                       <p class="name">Postal Code</p>
                        
                        <input type="text" class="email-field" placeholder="Enter your postal code">
                         <p class="name">Phone Number</p>
                        
                        <input type="tel" class="email-field" placeholder="Enter your phone number">
                         <p class="name">Password</p>
                          <input type="password" class="email-field" placeholder="Enter your password">
                           <p class="name">Confirm Password</p>
                          <input type="password" class="email-field" placeholder="Confirm your password">

                </div>
            </div>
            
            <div class="checkbox-div2">
                <input type="checkbox" id="checkbox">
                 <label for="checkbox">
                   <p class="keep-me-login-text">
                  I accept the <span>Terms of Use </span>and <span>Privacy Policy.</span>
                </p>
                </label>
  

                
            </div>
             <div class="button-div">
                <button class="login-button">Register Now</button>
            </div>
            
            <div class="dont-div">
                <p class="dont-you-text">Already Have an Account?</p>
                <a href="login.html" class="register">Login</a>
            </div>



        <div class="form-div">
            <div class="first-div">
                <div class="contact-info">
                    <div class="social-icons-div">

                        <div class="icons"><i class="fa fa-facebook-f"></i></div>
                        <div class="icons"> <i class="fa fa-twitter"></i></div>
                        <div class="icons"> <i class="fa fa-instagram"></i></div>


                    </div>

                    <div class="link-pages">
                        <a href="#" class="faq-page">FAQ</a>
                        <a href="#" class="faq-page">LEGAL</a>
                        <!-- Shopify But Button's div but it wont appear as display is none -->
                        <div id='product-component-1591813487900' style="display: none"></div>
                    </div>
                </div>

            </div>
            <div class="second-div">
                <p class="copyright-text">Copyright © 2020 staplesfast.com Inc. All rights reserved. </p>
            </div>
        </div>
    </div>
          <script>
        const toggleButton = document.getElementsByClassName('toggle-button')[0]
        const navbarLinks = document.getElementsByClassName('navbar-links2')[0]

        toggleButton.addEventListener('click', () => {
            navbarLinks.classList.toggle('active')
        })
    </script>
    <script type="text/javascript" src="{% static 'js/authPagesClickButton.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/shopifyBuyButton.js' %}"></script> <!-- Shopify Buy Button -->
    </body>
</html>